#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import re, sys
from main import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())

#dos2unix my_package
#for converting file my_package to Unix format...